- name: Install docker
  hosts: all
  become: true

  tasks:
    - name: Install docker dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: true

    - name: Add docker gpg key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add docker repository
      ansible.builtin.apt_repository:
        filename: docker
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | lower }} stable
        state: present

    - name: Install docker engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-buildx-plugin
          - docker-compose-plugin
          - python3-pip
        update_cache: true

    - name: Install Python Docker SDK
      ansible.builtin.apt:
        name: python3-docker
        state: present

    - name: Clone repository
      git:
        repo: https://github.com/TestAM245/bitmedia_test.git
        dest: /home/ubuntu/repo

    - name: Build container image
      community.docker.docker_image: 
        name: test-nginx
        build:
          path: /home/ubuntu/repo/NGINX
        source: build
        state: present
      
    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/repo/NGINX
        state: present